#!/usr/bin/env bash
# scorecard.sh — print a current harness-health snapshot (Markdown).
# Generated artifact: hand-maintained scorecards drift instantly, so compute
# the metrics instead. Save a dated snapshot with:
#   bash scripts/scorecard.sh > memory/scorecard/$(date +%Y-%m-%d)-snapshot.md
# Read-only report; intentionally not using `set -e`/pipefail (empty greps are
# expected, e.g. zero claude eval results).
set -u

REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "${REPO_DIR}"

count_md() { find "$1" -maxdepth 1 -name '*.md' ! -name 'README.md' 2>/dev/null | wc -l | tr -d ' '; }

agents_lines=$(wc -l < AGENTS.md | tr -d ' ')
claude_lines=$(wc -l < CLAUDE.md | tr -d ' ')
skills=$(ls skills/*/SKILL.md 2>/dev/null | wc -l | tr -d ' ')
subagents=$(ls subagents/*/AGENT.md 2>/dev/null | wc -l | tr -d ' ')
playbooks=$(count_md memory/playbooks)
decisions=$(count_md memory/decisions)
patterns=$(count_md memory/patterns)
troubleshooting=$(count_md memory/troubleshooting)
eval_tasks=$(ls evals/tasks/*.md 2>/dev/null | wc -l | tr -d ' ')
eval_results=$(find evals/results -type f -name '*.md' ! -name '.gitkeep' 2>/dev/null | wc -l | tr -d ' ')
eval_results_claude=$(grep -rl '^agent: *claude' evals/results 2>/dev/null | wc -l | tr -d ' ' || true)

cat <<EOF
# Harness Scorecard — $(date +%Y-%m-%d) (generated)

Generated by \`scripts/scorecard.sh\`. Do not hand-edit; regenerate instead.

| Metric | Value |
|---|---|
| AGENTS.md lines (always-on core) | ${agents_lines} |
| CLAUDE.md lines (always-on core) | ${claude_lines} |
| Skills | ${skills} |
| Subagents | ${subagents} |
| Playbooks | ${playbooks} |
| Decision records (ADRs) | ${decisions} |
| Patterns | ${patterns} |
| Troubleshooting records | ${troubleshooting} |
| Eval tasks | ${eval_tasks} |
| Eval results (total) | ${eval_results} |
| Eval results (claude) | ${eval_results_claude} |

Notes:
- Eval results are the evidence base for routing decisions; a low or
  single-agent count means the suite is under-fed (see evals/README "Status").
EOF
